# version: "3"
# services:  
#   djangoapp:
#     container_name: djangoapp
#     image: django
#     build:
#       context: .
#     ports:
#       - "80:80"
#     depends_on:
#       - db
#   db:
#     container_name: db
#     image: postgres:12
#     environment:
#       POSTGRES_USER: francesco
#       POSTGRES_PASSWORD: 12345
#       POSTGRES_DB: postgres
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/posgresql/data
# volumes:
#   pgdata:

version: "3.9"
   
services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db