# Generated by Django 2.0 on 2021-08-31 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_auto_20210831_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
